### PR TITLE
resize throws error Cannot read property 'getBoundingClientRect' 

### LINKED ISSUE #100: Cannot read property 'getBoundingClientRect' of null
Hi! 
I'm getting sometimes this error in console
```Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null```

How can I fix this?

image

### PR DESCRIPTION
**Pull request by daljeetv**
Great package! 

Using it quite a bit. This is to fix #100

### CODE REVIEW

**Comment by vanluke** [comment]
@daljeetv any updates on that?

**Comment by daljeetv** [comment]
just waiting to merge it

**Review by bfields-cpi — APPROVED** [review]
This seems like a reasonable check. LGTM.

**Comment by daljeetv** [comment]
@alexkatz do you mind merging this if it looks good to you?

**Comment by ilkerceng** [comment]
Hi @alexkatz, i got the same error on resize. It will be really helpful to merge if PR is ok.

**Comment by alexkatz** [comment]
Merged check for undefined child ref before popover positioning is attempted upon window resize. Will close for now. Thanks!

**Comment by fyoung-cpi** [comment]
Thanks @alexkatz for merging this.  Will you be publishing updated version to npm soon? Thanks again.

**Comment by ptaranto** [comment]
when will this be published to npm?

**Comment by ilkerceng** [comment]
Hi @alexkatz 
When i try to resize the window, i still get this error on version 6.0.6.

**Comment by ilkerceng** [comment]
@alexkatz I just installed 6.0.10 and it works now. Thanks.

**Pull request closed without merging**
