### PR TITLE
support server side rendering

### PR DESCRIPTION
**Pull request by meikidd**
Thank you @alexkatz for making this awesome package.

I am currently migrating my frontend project to server side rendering project. These few lines change can make this package work on server side.

It would be super cool if you can review and merge this PR.

### CODE REVIEW

**Comment by chrisvariety** [comment]
would love to see this merged, seeing the same issue.

**Comment by gregg-cbs** [comment]
Anyone want a quick fix, I wrapped Popover and did a check.

```
function Popover({children, ...bindProps}) {
  if (typeof window === 'undefined') return null;
  return (
    <ReactPopover
      {...bindProps}
    >
      {children}
    </ReactPopover>
  )
}

export default Popover
```

**Comment by benjaminbaldoni** [comment]
Any chance we get this one merged @alexkatz?

**Comment by alexkatz** [comment]
Closing this, as the PR violates a [basic principle](https://reactjs.org/docs/hooks-rules.html) of hooks.

**Comment by chrisvariety** [comment]
@alexkatz which principle?

**Comment by alexkatz** [comment]
Hooks cannot be called conditionally. React relies on the same number of hooks within a component to be called in the same order, every time, in order to keep track of them.

An early return statement based on a particular condition means that every hook to follow is called conditionally. This will [break your app](https://reactjs.org/warnings/invalid-hook-call-warning.html).

**Comment by alexkatz** [comment]
In regard to server side rendering, I recommend creating an HOC that handles it. It can look something like this:

```typescript
const SafePopover: FC<PopoverProps> = props => {
  if (typeof window === 'undefined') return props.children;
  return <Popover {...props} />;
};
```

**Comment by chrisvariety** [comment]
SSR isn't conditional though, does not violate the principle you have cited.

**Comment by GusRuss89** [comment]
@alexkatz why not export SafePopover as the default export from this library? As of now, anyone using this library in Next.js will google the error and end up at #118 which doesn't currently include an answer for this question. Next.js is popular, you're probably losing a lot of users.

**Pull request closed without merging**
