### PR TITLE
Removed usage of unstable_renderSubtreeIntoContainer

### PR DESCRIPTION
**Pull request by jmbastidas**
Context API does not work with ReactDOM.unstable_renderSubtreeIntoContainer, unstable_renderSubtreeIntoContainer has been superseded by Portals in React 16

### CODE REVIEW

**Comment by jmbastidas** [comment]
> Context API does not work with ReactDOM.unstable_renderSubtreeIntoContainer, unstable_renderSubtreeIntoContainer has been superseded by Portals in React 16

Also removes usage of componentWillMount

**Comment by odinho** [comment]
Would be great to get this in.

**Comment by laznic** [comment]
@alexkatz Could this get merged and published please?

**Comment by makker** [comment]
@alexkatz Would be great to get this merged and published?

**Comment by sirjuan** [comment]
@alexkatz Please merge this change :)

**Comment by HeikkiMoilanen** [comment]
@alexkatz Would be very nice to see this one merged :)

**Comment by alexkatz** [comment]
Working on fixing a few bugs introduced by this change. Stay tuned!

**Pull request merged**
